export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_CARS='FETCH_CARS';
export const FETCH_SINGLE_CAR='FETCH_SINGLE_CAR';
export const FETCH_FILTERED_CARS='FETCH_FILTERED_CARS';
export const FILTER_ACTIVATION='FILTER_ACTIVATION';
export const SELECTED_CAR = "SELECTED_CAR";
export const DELETE_CAR= "DELETE_CAR";

export const SAVE_CAR_SUCCESS="SAVE_CAR_SUCCESS";
export const SAVE_CAR_FAIL="SAVE_CAR_FAIL;"
export const FETCH_BRANDS = 'FETCH_BRANDS';

export const WISHLIST_ADD_PRODUCT='WISHLIST_ADD_PRODUCT';
export const WISHLIST_REMOVE_PRODUCT='WISHLIST_REMOVE_PRODUCT';
export const SELECTED_PRODUCT='SELECTED_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_SINGLE_PRODUCTS = 'FETCH_SINGLE_PRODUCTS';

export const BASKET_ADD = "BASKET_ADD";
export const BASKET_REMOVE_ITEM="BASKET_REMOVE_ITEM";
export const BASKET_EDIT_ITEM = "BASKET_EDIT_ITEM";

