INSERT INTO public.brand (id, name) VALUES (1, 'Volkswagen');
INSERT INTO public.brand (id, name) VALUES (2, 'Acura');
INSERT INTO public.brand (id, name) VALUES (3, 'Audi');
INSERT INTO public.brand (id, name) VALUES (4, 'BMW');
INSERT INTO public.brand (id, name) VALUES (19, 'Volkswagen');
INSERT INTO public.brand (id, name) VALUES (20, 'Volkswagen');
INSERT INTO public.brand (id, name) VALUES (21, 'BMW');
INSERT INTO public.brand (id, name) VALUES (22, 'BMW');
INSERT INTO public.brand (id, name) VALUES (23, 'some brand');
INSERT INTO public.brand (id, name) VALUES (24, 'BMW');
INSERT INTO public.brand (id, name) VALUES (25, 'some brand');