INSERT INTO public.car (id, name, brand_id) VALUES (1, '2021 Volkswagen Tiguan', 1);
INSERT INTO public.car (id, name, brand_id) VALUES (2, 'Volkswagen ID.6', 1);
INSERT INTO public.car (id, name, brand_id) VALUES (3, 'Golf MK4', 1);
INSERT INTO public.car (id, name, brand_id) VALUES (4, '2022 Acura MDX', 2);
INSERT INTO public.car (id, name, brand_id) VALUES (5, 'MDX-4-2022', 2);
INSERT INTO public.car (id, name, brand_id) VALUES (6, 'Twin-Turbo', 2);
INSERT INTO public.car (id, name, brand_id) VALUES (7, 'Hybrid-V6', 2);
INSERT INTO public.car (id, name, brand_id) VALUES (8, 'A1', 3);
INSERT INTO public.car (id, name, brand_id) VALUES (9, '80', 3);
INSERT INTO public.car (id, name, brand_id) VALUES (10, 'Aicon', 3);
INSERT INTO public.car (id, name, brand_id) VALUES (11, 'Gran Coupe', 4);
INSERT INTO public.car (id, name, brand_id) VALUES (12, '5', 4);
INSERT INTO public.car (id, name, brand_id) VALUES (13, '6', 4);
INSERT INTO public.car (id, name, brand_id) VALUES (15, 'Golf 4', 19);
INSERT INTO public.car (id, name, brand_id) VALUES (16, 'Golf 4', 20);
INSERT INTO public.car (id, name, brand_id) VALUES (17, '19', 21);
INSERT INTO public.car (id, name, brand_id) VALUES (18, '19', 22);
INSERT INTO public.car (id, name, brand_id) VALUES (19, 'Some name', 23);
INSERT INTO public.car (id, name, brand_id) VALUES (20, '19', 24);
INSERT INTO public.car (id, name, brand_id) VALUES (21, 'Some name', 25);